FROM node:18-alpine

WORKDIR /app

COPY ./package*.json /app/

RUN npm install

COPY . /app/

ENV DATABASE_URL=postgres://your_database_user:your_database_password@db:5432/your_database_name

EXPOSE 3001

CMD ["npm", "run", "dev"]
