version: "3"
services:
  db:
    image: postgres
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rathod1234vikas
      POSTGRES_DB: v-chat
    ports:
      - "5432:5432"

  prisma:
    image: v-chat/client # Replace with the appropriate image for Prisma migrations
    container_name: my_prisma_migration
    environment:
      DATABASE_URL: postgres://postgres:rathod1234vikas@db:5432/v-chat
    depends_on:
      - db
    volumes:
      - ./src/prisma:/app/src/prisma
      - ./node_modules/@prisma/client:/app/node_modules/@prisma/client
    command: "npx prisma migrate dev --schema=/app/src/prisma/schema.prisma"
  # command: sh -c "npx prisma migrate dev --schema=/app/src/prisma/schema.prisma && npx prisma generate --schema=/app/src/prisma/schema.prisma"

  app:
    image: v-chat/client
    ports:
      - "3002:3001"
    depends_on:
      - prisma # Ensure that the app service depends on the Prisma migration service
